# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  # baseURL: https://io-33kyanite.github.io/sasaki/
  languageCode: en-us
  contentDir: content/tmp

# Uncomment the lines below to configure your website in a second language.
ja:
  # baseURL: https://io-33kyanite.github.io/sasaki/ja/
  languageCode: ja-jp
  contentDir: content/tmp
  title: Iori' Profile
  params:
    description: 'Ioriのプロフィール'

#zh:
#  languageCode: zh-Hans
#  contentDir: content/zh
#  title: Chinese website title...
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
